name: Deploy to ECS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Log in to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private
          mask-password: true
        env:
          ACTIONS_STEP_DEBUG: true
      - name: Verify Docker Context and Login
        run: |
          docker context use default
          docker info --format '{{.ClientInfo.Context}}'  # Should print "default"
          docker login -u AWS -p $(aws ecr get-login-password --region ap-southeast-1) 631229639219.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build, Tag, and Push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: 631229639219.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com  # Match secrets.AWS_DEFAULT_REGION
          ECR_REPOSITORY: hello-world-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Download Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./terraform